version: "3.8"

services:
  kafkaUserServiceTest:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafkaUserServiceTest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeperUserServiceTest
    restart: always

  zookeeperUserServiceTest:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeperUserServiceTest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    restart: always

  userservicetest:
    build: .
    container_name: UserServiceTest
    depends_on:
      - kafkaUserServiceTest
    environment:
      - CONFIG_PATH=/app/config.yaml
      - KAFKA_BROKER=kafka:9092
    volumes:
      - ./config/local.yaml:/app/config.yaml
    restart: always
